/**
 * Route the static documentation shell and migrated React algorithm workbenches.
 *
 * @file
 */

import { index, route } from "@react-router/dev/routes";
import type { RouteConfig } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx")
	, route("demos", "routes/gallery.tsx")
	, route("demos/lean-myers", "routes/myers.tsx")
	, route("demos/lean-sweep-and-prune", "routes/sweep.tsx")
	, route("demos/lean-dinic", "routes/dinic.tsx")
	, route("demos/lean-dijkstra", "routes/dijkstra.tsx")
	, route("demos/lean-flood-fill", "routes/flood-fill.tsx")
	, route("demos/lean-union-find", "routes/union-find.tsx")
	, route("demos/lean-topological-sort", "routes/topological-sort.tsx")
	, route("demos/lean-aho-corasick", "routes/aho-corasick.tsx")
	, route("demos/lean-lru-cache", "routes/lru-cache.tsx")
	, route("demos/lean-a-star", "routes/a-star.tsx")
	, route("demos/lean-tarjan", "routes/tarjan.tsx")
	, route("demos/lean-token-bucket", "routes/token-bucket.tsx")
	, route("docs", "routes/guides/documentation.tsx")
	, route("docs/lean", "routes/guides/lean-author.tsx")
	, route("docs/lean/setup", "routes/guides/lean-setup.tsx")
	, route("docs/lean/first-component", "routes/guides/lean-first-component.tsx")
	, route("docs/lean/proofs-and-assurance", "routes/guides/lean-proofs.tsx")
	, route("docs/lean/export-decisions", "routes/guides/lean-exports.tsx")
	, route("docs/lean/diagnostics", "routes/guides/lean-diagnostics.tsx")
	, route("docs/consume", "routes/guides/consume.tsx")
	, route("docs/consume/receive-package", "routes/guides/receive-package.tsx")
	, route("docs/consume/javascript", "routes/guides/javascript.tsx")
	, route("docs/consume/typescript", "routes/guides/typescript.tsx")
	, route("docs/consume/browser", "routes/guides/browser.tsx")
	, route("docs/consume/python", "routes/guides/python.tsx")
	, route("docs/consume/rust", "routes/guides/rust.tsx")
	, route("docs/consume/c", "routes/guides/c.tsx")
	, route("docs/consume/cpp", "routes/guides/cpp.tsx")
	, route("docs/consume/dotnet", "routes/guides/dotnet.tsx")
	, route("docs/consume/java", "routes/guides/java.tsx")
	, route("docs/consume/kotlin", "routes/guides/kotlin.tsx")
	, route("docs/consume/ruby", "routes/guides/ruby.tsx")
	, route("docs/consume/php-native", "routes/guides/php-native.tsx")
	, route("docs/consume/php-wasm", "routes/guides/php-wasm.tsx")
	, route("docs/consume/wit-wasi", "routes/guides/wit-wasi.tsx")
	, route("docs/consume/javascript-typescript", "routes/guides/javascript-typescript.tsx")
	, route("docs/consume/react", "routes/guides/react.tsx")
	, route("docs/consume/browser-workers", "routes/guides/browser-workers.tsx")
	, route("docs/consume/demo-api", "routes/guides/demo-api.tsx")
	, route("docs/consume/php", "routes/guides/php.tsx")
	, route("docs/consume/dotnet-jvm-ruby", "routes/guides/dotnet-jvm-ruby.tsx")
	, route("docs/consume/runtimes", "routes/guides/runtimes.tsx")
	, route("docs/publish", "routes/guides/publish.tsx")
	, route("docs/publish/local-handoff", "routes/guides/publish-local.tsx")
	, route("docs/publish/sandbox-release", "routes/guides/publish-sandbox.tsx")
	, route("docs/publish/production-release", "routes/guides/publish-production.tsx")
	, route("docs/publish/npm", "routes/guides/publish-npm.tsx")
	, route("docs/publish/pypi", "routes/guides/publish-pypi.tsx")
	, route("docs/publish/cargo", "routes/guides/publish-cargo.tsx")
	, route("docs/publish/nuget", "routes/guides/publish-nuget.tsx")
	, route("docs/publish/maven", "routes/guides/publish-maven.tsx")
	, route("docs/publish/rubygems", "routes/guides/publish-rubygems.tsx")
	, route("docs/publish/composer", "routes/guides/publish-composer.tsx")
	, route("docs/publish/archives", "routes/guides/publish-archives.tsx")
	, route("docs/publish/nix", "routes/guides/publish-nix.tsx")
	, route("docs/publish/github-pages", "routes/guides/publish-pages.tsx")
	, route("docs/publish/pipeline", "routes/guides/release-pipeline.tsx")
	, route("docs/contributing", "routes/guides/contributing.tsx")
	, route("docs/contributing/documentation", "routes/guides/contributing-documentation.tsx")
	, route("docs/contributing/demos", "routes/guides/contributing-demos.tsx")
	, route("docs/contributing/testing", "routes/guides/contributing-testing.tsx")
	, route("docs/contributing/release-pipeline", "routes/guides/contributing-release-pipeline.tsx")
	, route("docs/contributing/github-pages", "routes/guides/contributing-pages.tsx")
	, route("docs/concepts/lean-to-wasm", "routes/guides/proof-to-wasm.tsx")
	, route("docs/concepts/benchmarks", "routes/guides/benchmarks.tsx")
	, route("docs/concepts", "routes/guides/concepts.tsx")
	, route("docs/concepts/change-risk", "routes/guides/change-risk.tsx")
	, route("docs/concepts/auditable-claims", "routes/guides/auditable-claims.tsx")
	, route("docs/concepts/reusable-cores", "routes/guides/reusable-cores.tsx")
	, route("docs/concepts/trust-boundaries", "routes/guides/trust-boundaries.tsx")
	, route("docs/concepts/shared-runtime", "routes/guides/shared-runtime.tsx")
	, route("docs/concepts/ownership", "routes/guides/ownership.tsx")
	, route("docs/concepts/adoption", "routes/guides/adoption.tsx")
	, route("docs/concepts/dijkstra", "routes/guides/dijkstra-explained.tsx")
	, route("docs/concepts/flood-fill", "routes/guides/flood-fill-explained.tsx")
	, route("docs/reference/cli", "routes/guides/reference-cli.tsx")
	, route("docs/reference/package-api", "routes/guides/reference-package-api.tsx")
	, route("docs/reference/types", "routes/guides/reference-types.tsx")
	, route("docs/reference/algorithms", "routes/guides/reference-algorithms.tsx")
	, route("status", "routes/guides/status.tsx")
	, route("*", "routes/not-found.tsx")
] satisfies RouteConfig;
